interface Product {
  name: string;
  price: number;
  origin: string;
  description: string;
  category: string;
}

export const products: Product[] = [
  {
    name: "프리미엄 사료 5kg",
    price: 35000,
    origin: "국내산",
    category: "애완동물",
    description: "고단백 저지방 프리미엄 반려견 전용 사료",
  },
  {
    name: "공기청정기 20평",
    price: 189000,
    origin: "국내산",
    category: "가전제품",
    description: "헤파 필터 탑재 20평형 인버터 공기청정기",
  },
  {
    name: "유기농 쌀 5kg",
    price: 28000,
    origin: "국내산",
    category: "음식",
    description: "전라남도 해남 친환경 인증 유기농 백미 5kg",
  },
  {
    name: "남성 기본 티셔츠",
    price: 19000,
    origin: "국내산",
    category: "의류",
    description: "20수 순면 소재 남성 라운드넥 기본 반팔 티셔츠",
  },
  {
    name: "종합 비타민 60정",
    price: 28000,
    origin: "국내산",
    category: "건강",
    description: "남녀공용 하루 한 알 먹는 종합 비타민 미네랄 60정",
  },
  {
    name: "주방 세제 1L",
    price: 5500,
    origin: "국내산",
    category: "생활용품",
    description: "식물성 계면활성제 저자극 주방용 설거지 세제 1L",
  },
  {
    name: "고양이 캔 참치맛",
    price: 2500,
    origin: "태국산",
    category: "애완동물",
    description: "참치 함량 70% 이상의 고양이 습식 캔 사료",
  },
  {
    name: "미니 선풍기",
    price: 28000,
    origin: "중국산",
    category: "가전제품",
    description: "USB 충전식 3단 속도 조절 미니 탁상 선풍기",
  },
  {
    name: "냉동 삼겹살 500g",
    price: 14500,
    origin: "국내산",
    category: "음식",
    description: "두께 1cm 슬라이스 국내산 냉동 삼겹살 500g",
  },
  {
    name: "여성 슬랙스 팬츠",
    price: 45000,
    origin: "국내산",
    category: "의류",
    description: "허리 밴드 조절 가능한 여성 와이드 슬랙스 팬츠",
  },
  {
    name: "비타민C 1000mg",
    price: 18000,
    origin: "국내산",
    category: "건강",
    description: "고함량 비타민C 1000mg 항산화 면역 강화 90정",
  },
  {
    name: "세탁 세제 3kg",
    price: 18000,
    origin: "국내산",
    category: "생활용품",
    description: "효소 성분 함유 드럼 통돌이 겸용 세탁 세제 3kg",
  },
  {
    name: "강아지 간식 육포",
    price: 8900,
    origin: "국내산",
    category: "애완동물",
    description: "무방부제 천연 닭고기 육포 간식",
  },
  {
    name: "전기포트 1.7L",
    price: 35000,
    origin: "국내산",
    category: "가전제품",
    description: "온도 유지 기능 탑재 1.7L 스테인리스 전기포트",
  },
  {
    name: "제주 감귤 3kg",
    price: 18000,
    origin: "제주산",
    category: "음식",
    description: "새콤달콤 제주 직송 흙귤 감귤 3kg 선물 세트",
  },
  {
    name: "남성 청바지",
    price: 55000,
    origin: "국내산",
    category: "의류",
    description: "스트레치 데님 소재 슬림 핏 남성 청바지",
  },
  {
    name: "프로바이오틱스 30포",
    price: 35000,
    origin: "국내산",
    category: "건강",
    description: "10억 유산균 포함 장 건강 개선 프로바이오틱스 30포",
  },
  {
    name: "욕실 청소 스프레이",
    price: 6500,
    origin: "국내산",
    category: "생활용품",
    description: "곰팡이 물때 제거 욕실 전용 산성 청소 스프레이",
  },
  {
    name: "고양이 모래 10L",
    price: 12000,
    origin: "국내산",
    category: "애완동물",
    description: "탈취력이 뛰어난 벤토나이트 고양이 모래",
  },
  {
    name: "블루투스 스피커",
    price: 55000,
    origin: "중국산",
    category: "가전제품",
    description: "방수 기능의 360도 서라운드 블루투스 스피커",
  },
  {
    name: "건강 그래놀라",
    price: 12000,
    origin: "국내산",
    category: "음식",
    description: "견과류와 꿀로 만든 저당 오트밀 건강 그래놀라",
  },
  {
    name: "여성 블라우스",
    price: 38000,
    origin: "국내산",
    category: "의류",
    description: "실크 터치 소재 리본 넥 여성 기본 블라우스",
  },
  {
    name: "오메가3 60캡슐",
    price: 25000,
    origin: "노르웨이산",
    category: "건강",
    description: "EPA DHA 고함량 어유 기반 오메가3 60캡슐",
  },
  {
    name: "행주 10매 세트",
    price: 9000,
    origin: "국내산",
    category: "생활용품",
    description: "순면 이중직 항균 처리 주방 전용 행주 10매 세트",
  },
  {
    name: "반려견 목욕 샴푸",
    price: 15000,
    origin: "국내산",
    category: "애완동물",
    description: "민감한 피부를 위한 저자극 반려견 샴푸",
  },
  {
    name: "무선 청소기",
    price: 235000,
    origin: "국내산",
    category: "가전제품",
    description: "흡입력 25000Pa 이상의 코드리스 무선 청소기",
  },
  {
    name: "국내산 꿀 500g",
    price: 22000,
    origin: "국내산",
    category: "음식",
    description: "아카시아 100% 국내산 자연 채취 천연 꿀 500g",
  },
  {
    name: "남성 맨투맨",
    price: 35000,
    origin: "국내산",
    category: "의류",
    description: "20수 기모 안감 라운드넥 오버핏 남성 맨투맨",
  },
  {
    name: "루테인 30정",
    price: 22000,
    origin: "국내산",
    category: "건강",
    description: "눈 건강 황반 색소 보호 루테인 20mg 30정",
  },
  {
    name: "고무장갑 M 사이즈",
    price: 3500,
    origin: "국내산",
    category: "생활용품",
    description: "라텍스 소재 내구성 높은 주방 청소 고무장갑 M",
  },
  {
    name: "펫 자동 급수기",
    price: 28000,
    origin: "중국산",
    category: "애완동물",
    description: "필터 내장 자동 순환 방식 펫 급수기",
  },
  {
    name: "전자레인지 20L",
    price: 89000,
    origin: "국내산",
    category: "가전제품",
    description: "그릴 기능 탑재 20L 단독형 전자레인지",
  },
  {
    name: "들기름 400ml",
    price: 16000,
    origin: "국내산",
    category: "음식",
    description: "저온 압착 방식 국내산 들깨 100% 들기름",
  },
  {
    name: "여성 원피스",
    price: 52000,
    origin: "국내산",
    category: "의류",
    description: "A라인 플레어 미디 길이 여성 민소매 원피스",
  },
  {
    name: "마그네슘 90정",
    price: 19000,
    origin: "국내산",
    category: "건강",
    description: "근육 이완 및 수면 개선 도움 마그네슘 영양제 90정",
  },
  {
    name: "수세미 5개 세트",
    price: 5000,
    origin: "국내산",
    category: "생활용품",
    description: "양면 스펀지 수세미 항균 코팅 5개 묶음 세트",
  },
  {
    name: "고양이 스크래처",
    price: 18000,
    origin: "국내산",
    category: "애완동물",
    description: "천연 사이잘 재질의 고양이 스크래처",
  },
  {
    name: "에어프라이어 5L",
    price: 79000,
    origin: "중국산",
    category: "가전제품",
    description: "디지털 터치 패널 탑재 5L 대용량 에어프라이어",
  },
  {
    name: "냉동 만두 500g",
    price: 8900,
    origin: "국내산",
    category: "음식",
    description: "김치 돼지고기 듬뿍 넣은 국내산 냉동 왕만두",
  },
  {
    name: "유니섹스 후디",
    price: 42000,
    origin: "국내산",
    category: "의류",
    description: "기모 안감 캥거루 포켓 유니섹스 집업 후디",
  },
  {
    name: "철분 보충제 30정",
    price: 16000,
    origin: "국내산",
    category: "건강",
    description: "흡수율 높은 헴철 성분 여성 철분 보충 영양제 30정",
  },
  {
    name: "압축 쓰레기봉투 10L",
    price: 4500,
    origin: "국내산",
    category: "생활용품",
    description: "규격 납부필증 쓰레기 종량제 봉투 10L 10매",
  },
  {
    name: "강아지 입마개",
    price: 9500,
    origin: "국내산",
    category: "애완동물",
    description: "통기성 좋은 메쉬 소재 강아지 입마개",
  },
  {
    name: "로봇청소기",
    price: 349000,
    origin: "국내산",
    category: "가전제품",
    description: "자동 복귀 충전 기능의 레이저 매핑 로봇청소기",
  },
  {
    name: "참기름 200ml",
    price: 12000,
    origin: "국내산",
    category: "음식",
    description: "국내산 참깨 100% 전통 방식 압착 참기름",
  },
  {
    name: "남성 면 반바지",
    price: 28000,
    origin: "국내산",
    category: "의류",
    description: "순면 소재 허리 드로스트링 남성 하프 반바지",
  },
  {
    name: "콜라겐 파우더 100g",
    price: 32000,
    origin: "국내산",
    category: "건강",
    description: "저분자 어류 콜라겐 피부 탄력 피부 콜라겐 파우더",
  },
  {
    name: "지퍼백 대형 10매",
    price: 3800,
    origin: "국내산",
    category: "생활용품",
    description: "냉동 냉장 겸용 밀폐 이중 지퍼백 대형 10매 세트",
  },
  {
    name: "반려묘 장난감 낚싯대",
    price: 7000,
    origin: "국내산",
    category: "애완동물",
    description: "깃털 달린 인터랙티브 고양이 낚싯대 장난감",
  },
  {
    name: "드립 커피 머신",
    price: 125000,
    origin: "국내산",
    category: "가전제품",
    description: "보온 플레이트 내장 8인용 드립 커피 머신",
  },
  {
    name: "건 미역 100g",
    price: 7500,
    origin: "국내산",
    category: "음식",
    description: "남해 완도산 햇 미역 자연 건조 건 미역 100g",
  },
  {
    name: "여성 레깅스",
    price: 25000,
    origin: "국내산",
    category: "의류",
    description: "고탄력 나일론 소재 허리 밴드 여성 기본 레깅스",
  },
  {
    name: "아르기닌 90캡슐",
    price: 29000,
    origin: "국내산",
    category: "건강",
    description: "L-아르기닌 3000mg 혈행 개선 운동 성능 영양제",
  },
  {
    name: "실리콘 주방 집게",
    price: 6500,
    origin: "국내산",
    category: "생활용품",
    description: "내열 250도 미끄럼 방지 실리콘 멀티 주방 집게",
  },
  {
    name: "펫 이동 가방",
    price: 42000,
    origin: "국내산",
    category: "애완동물",
    description: "항공기 탑승 가능한 펫 이동용 캐리어 가방",
  },
  {
    name: "가정용 제습기",
    price: 215000,
    origin: "국내산",
    category: "가전제품",
    description: "하루 12L 제습 능력의 가정용 인버터 제습기",
  },
  {
    name: "국산 잡곡 1kg",
    price: 11000,
    origin: "국내산",
    category: "음식",
    description: "10가지 국산 잡곡 혼합 혼합 잡곡 1kg",
  },
  {
    name: "남성 폴로 티셔츠",
    price: 38000,
    origin: "국내산",
    category: "의류",
    description: "피케 소재 카라 버튼 남성 반팔 폴로 셔츠",
  },
  {
    name: "글루타민 분말 300g",
    price: 28000,
    origin: "국내산",
    category: "건강",
    description: "근육 회복 면역력 개선 L-글루타민 파우더 300g",
  },
  {
    name: "도마 항균 플라스틱",
    price: 12000,
    origin: "국내산",
    category: "생활용품",
    description: "항균 PE 소재 양면 사용 가능 가정용 주방 도마",
  },
  {
    name: "강아지 방석 쿠션",
    price: 22000,
    origin: "국내산",
    category: "애완동물",
    description: "메모리폼 소재의 정형외과용 강아지 방석",
  },
  {
    name: "핸드 믹서기",
    price: 42000,
    origin: "국내산",
    category: "가전제품",
    description: "5단 속도 조절 가능한 스탠드 핸드 믹서기",
  },
  {
    name: "냉동 새우 500g",
    price: 13800,
    origin: "베트남산",
    category: "음식",
    description: "껍질 제거 IQF 방식 냉동 블랙 타이거 새우 500g",
  },
  {
    name: "여성 트렌치코트",
    price: 95000,
    origin: "국내산",
    category: "의류",
    description: "벨트 포함 더블 버튼 여성 봄가을 트렌치코트",
  },
  {
    name: "홍삼 진액 30포",
    price: 65000,
    origin: "국내산",
    category: "건강",
    description: "6년근 홍삼 농축 진액 면역 피로 개선 30포 세트",
  },
  {
    name: "욕실 발판 매트",
    price: 14000,
    origin: "국내산",
    category: "생활용품",
    description: "규조토 소재 빠른 흡수 미끄럼 방지 욕실 발판 매트",
  },
  {
    name: "고양이 캣타워",
    price: 65000,
    origin: "국내산",
    category: "애완동물",
    description: "5단 구조의 스크래처 내장 고양이 캣타워",
  },
  {
    name: "전기면도기",
    price: 68000,
    origin: "국내산",
    category: "가전제품",
    description: "방수 기능 탑재 충전식 왕복 전기면도기",
  },
  {
    name: "저염 간장 500ml",
    price: 6500,
    origin: "국내산",
    category: "음식",
    description: "나트륨 40% 저감 전통 방식 양조 저염 간장",
  },
  {
    name: "남성 가디건",
    price: 48000,
    origin: "국내산",
    category: "의류",
    description: "울 혼방 소재 V넥 단추형 남성 기본 가디건",
  },
  {
    name: "계피 추출물 30정",
    price: 21000,
    origin: "국내산",
    category: "건강",
    description: "혈당 조절 도움 계피 추출물 MHCP 성분 영양제",
  },
  {
    name: "샤워기 필터",
    price: 18000,
    origin: "국내산",
    category: "생활용품",
    description: "녹물 염소 제거 비타민C 필터 샤워 필터 헤드",
  },
  {
    name: "펫 발 세정제",
    price: 11000,
    origin: "국내산",
    category: "애완동물",
    description: "외출 후 간편하게 사용하는 펫 발 전용 세정제",
  },
  {
    name: "휴대용 선풍기",
    price: 22000,
    origin: "중국산",
    category: "가전제품",
    description: "접이식 목걸이 타입 충전식 휴대용 선풍기",
  },
  {
    name: "국산 된장 500g",
    price: 8000,
    origin: "국내산",
    category: "음식",
    description: "재래식 메주로 만든 3년 숙성 국산 재래 된장",
  },
  {
    name: "여성 청바지 스키니",
    price: 49000,
    origin: "국내산",
    category: "의류",
    description: "스트레치 데님 하이웨이스트 여성 스키니 청바지",
  },
  {
    name: "아연 60정",
    price: 14000,
    origin: "국내산",
    category: "건강",
    description: "면역력 남성 건강 아연 25mg 함유 영양제 60정",
  },
  {
    name: "변기 세정제",
    price: 4000,
    origin: "국내산",
    category: "생활용품",
    description: "살균 탈취 자동 세정 변기 걸이형 세정 블록",
  },
  {
    name: "반려견 리드줄",
    price: 13000,
    origin: "국내산",
    category: "애완동물",
    description: "신축성 있는 3m 자동 릴 반려견 리드줄",
  },
  {
    name: "전기 찜기",
    price: 48000,
    origin: "중국산",
    category: "가전제품",
    description: "3단 트레이 구성 3.5L 대용량 전기 찜기",
  },
  {
    name: "올리브 오일 500ml",
    price: 19000,
    origin: "스페인산",
    category: "음식",
    description: "엑스트라 버진 등급 콜드 프레스 올리브 오일",
  },
  {
    name: "남성 린넨 셔츠",
    price: 42000,
    origin: "국내산",
    category: "의류",
    description: "100% 린넨 소재 루즈핏 남성 여름 반팔 셔츠",
  },
  {
    name: "비타민D 90정",
    price: 18000,
    origin: "국내산",
    category: "건강",
    description: "뼈 건강 칼슘 흡수 비타민D3 2000IU 90정",
  },
  {
    name: "방향제 자동차용",
    price: 8000,
    origin: "국내산",
    category: "생활용품",
    description: "천연 향 추출 차 내부 환기 클립형 자동차 방향제",
  },
  {
    name: "고양이 습식 사료",
    price: 3200,
    origin: "태국산",
    category: "애완동물",
    description: "연어 함량 65% 고단백 고양이 습식 파우치",
  },
  {
    name: "무선 이어폰",
    price: 89000,
    origin: "국내산",
    category: "가전제품",
    description: "노이즈캔슬링 기능 탑재 TWS 무선 이어폰",
  },
  {
    name: "프리미엄 소금",
    price: 9500,
    origin: "국내산",
    category: "음식",
    description: "신안 천일염 3년 간수 빼기 프리미엄 토판염",
  },
  {
    name: "여성 니트 스웨터",
    price: 55000,
    origin: "국내산",
    category: "의류",
    description: "울 60% 혼방 라운드넥 여성 크롭 니트 스웨터",
  },
  {
    name: "밀크씨슬 30정",
    price: 23000,
    origin: "국내산",
    category: "건강",
    description: "간 건강 보호 실리마린 성분 밀크씨슬 추출물 30정",
  },
  {
    name: "빨래 건조대 접이식",
    price: 35000,
    origin: "국내산",
    category: "생활용품",
    description: "스테인리스 접이식 대형 실내 빨래 건조대",
  },
  {
    name: "강아지 치석제거 껌",
    price: 6500,
    origin: "뉴질랜드산",
    category: "애완동물",
    description: "효소 함유 덴탈 치석 제거용 강아지 껌",
  },
  {
    name: "전기그릴 2인용",
    price: 55000,
    origin: "국내산",
    category: "가전제품",
    description: "착탈 가능 플레이트 탑재 2인용 전기 그릴",
  },
  {
    name: "냉동 블루베리 1kg",
    price: 17000,
    origin: "칠레산",
    category: "음식",
    description: "당도 높은 칠레산 IQF 냉동 블루베리 1kg",
  },
  {
    name: "남성 조거 팬츠",
    price: 38000,
    origin: "국내산",
    category: "의류",
    description: "면 혼방 밴드 허리 남성 테이퍼드 조거 팬츠",
  },
  {
    name: "엽산 90정",
    price: 12000,
    origin: "국내산",
    category: "건강",
    description: "임산부 필수 엽산 400mcg 세포 생성 도움 90정",
  },
  {
    name: "스텐 밀폐용기 3종",
    price: 22000,
    origin: "국내산",
    category: "생활용품",
    description: "STS304 스테인리스 냄비 보관 밀폐 용기 3종 세트",
  },
  {
    name: "펫 항균 스프레이",
    price: 9800,
    origin: "국내산",
    category: "애완동물",
    description: "냄새 및 세균 제거용 반려동물 전용 항균 스프레이",
  },
  {
    name: "스마트 체중계",
    price: 38000,
    origin: "중국산",
    category: "가전제품",
    description: "체지방 측정 가능한 앱 연동 스마트 체중계",
  },
  {
    name: "오트밀 1kg",
    price: 8500,
    origin: "호주산",
    category: "음식",
    description: "글루텐 프리 인증 퀵 쿡 롤드 오트밀 1kg",
  },
  {
    name: "여성 탑 민소매",
    price: 22000,
    origin: "국내산",
    category: "의류",
    description: "모달 소재 루즈핏 여성 기본 민소매 탑",
  },
  {
    name: "코큐텐 60정",
    price: 32000,
    origin: "국내산",
    category: "건강",
    description: "항산화 심장 건강 코엔자임큐텐 100mg 60정",
  },
  {
    name: "커튼 암막 1.5m",
    price: 28000,
    origin: "국내산",
    category: "생활용품",
    description: "차광율 99% 단열 방음 기능 암막 커튼 1.5m 2장",
  },
  {
    name: "고양이 자동 급식기",
    price: 55000,
    origin: "중국산",
    category: "애완동물",
    description: "타이머 예약 기능 탑재 고양이 자동 급식기",
  },
  {
    name: "안마 쿠션",
    price: 72000,
    origin: "중국산",
    category: "가전제품",
    description: "지압 롤러 내장 열선 포함 전신 안마 쿠션",
  },
  {
    name: "국내산 흑마늘",
    price: 24000,
    origin: "국내산",
    category: "음식",
    description: "남해 마늘 30일 숙성 국내산 흑마늘 1kg",
  },
  {
    name: "남성 수영복",
    price: 32000,
    origin: "국내산",
    category: "의류",
    description: "클로린 저항 소재 보드숏 타입 남성 수영복",
  },
  {
    name: "칼슘 마그네슘 90정",
    price: 22000,
    origin: "국내산",
    category: "건강",
    description: "골다공증 예방 칼슘 마그네슘 아연 비타민D 복합 90정",
  },
  {
    name: "형광등 LED 교체용",
    price: 15000,
    origin: "국내산",
    category: "생활용품",
    description: "에너지 소비 효율 1등급 18W LED 형광등 교체품",
  },
  {
    name: "반려견 하네스",
    price: 19000,
    origin: "국내산",
    category: "애완동물",
    description: "가슴 보호 설계의 소형견 전용 하네스",
  },
  {
    name: "가정용 제빙기",
    price: 135000,
    origin: "중국산",
    category: "가전제품",
    description: "하루 12kg 생산 능력의 가정용 소형 제빙기",
  },
  {
    name: "참치 캔 3입 세트",
    price: 7800,
    origin: "원양산",
    category: "음식",
    description: "살코기 100% 기름 적은 원양산 참치 캔 3입",
  },
  {
    name: "여성 수영복",
    price: 45000,
    origin: "국내산",
    category: "의류",
    description: "UPF 50+ 자외선 차단 원피스 여성 래쉬가드",
  },
  {
    name: "눈 건강 안토시아닌",
    price: 28000,
    origin: "국내산",
    category: "건강",
    description: "빌베리 아사이베리 눈 피로 개선 안토시아닌 영양제",
  },
  {
    name: "배수구 필터 10개",
    price: 5500,
    origin: "국내산",
    category: "생활용품",
    description: "머리카락 음식물 차단 싱크대 욕실 배수구 필터 10개",
  },
  {
    name: "펫 구충제",
    price: 14000,
    origin: "국내산",
    category: "애완동물",
    description: "내외부 기생충 동시 구제 펫 구충제",
  },
  {
    name: "전기 히터",
    price: 65000,
    origin: "국내산",
    category: "가전제품",
    description: "과열 방지 기능 탑재 PTC 세라믹 전기 히터",
  },
  {
    name: "두부 400g",
    price: 2800,
    origin: "국내산",
    category: "음식",
    description: "국산 콩 100% 사용 비응고제 순두부 400g",
  },
  {
    name: "남성 파자마 세트",
    price: 42000,
    origin: "국내산",
    category: "의류",
    description: "순면 소재 상하 세트 남성 긴소매 파자마",
  },
  {
    name: "쏘팔메토 30정",
    price: 38000,
    origin: "미국산",
    category: "건강",
    description: "전립선 건강 쏘팔메토 오일 320mg 성분 30정",
  },
  {
    name: "소파 방수 커버",
    price: 32000,
    origin: "국내산",
    category: "생활용품",
    description: "방수 방오 처리 탄성 밴드 소파 전용 방수 커버",
  },
  {
    name: "고양이 간식 트릿",
    price: 4500,
    origin: "국내산",
    category: "애완동물",
    description: "치즈 맛 고양이 전용 소프트 트릿 간식",
  },
  {
    name: "스탠드 조명",
    price: 45000,
    origin: "국내산",
    category: "가전제품",
    description: "밝기 5단계 조절 LED 터치 스탠드 조명",
  },
  {
    name: "제주 한라봉 2kg",
    price: 22000,
    origin: "제주산",
    category: "음식",
    description: "당도 12브릭스 이상 제주산 한라봉 2kg",
  },
  {
    name: "여성 파자마 세트",
    price: 45000,
    origin: "국내산",
    category: "의류",
    description: "모달 소재 플라워 패턴 여성 잠옷 파자마 세트",
  },
  {
    name: "녹차 추출물 60정",
    price: 19000,
    origin: "국내산",
    category: "건강",
    description: "카테킨 EGCG 성분 항산화 체지방 감소 녹차 추출물",
  },
  {
    name: "칫솔 홀더 흡착식",
    price: 9000,
    origin: "국내산",
    category: "생활용품",
    description: "강력 흡착판 5구 욕실 벽 부착 칫솔 홀더",
  },
  {
    name: "강아지 겨울 옷",
    price: 17000,
    origin: "국내산",
    category: "애완동물",
    description: "방한 기능의 소형견 겨울 점퍼 의류",
  },
  {
    name: "USB 허브 7포트",
    price: 28000,
    origin: "중국산",
    category: "가전제품",
    description: "USB 3.0 지원 7포트 알루미늄 허브",
  },
  {
    name: "국산 잣 200g",
    price: 16000,
    origin: "국내산",
    category: "음식",
    description: "강원도 홍천 국산 백잣 200g 영양 간식",
  },
  {
    name: "남성 겨울 패딩",
    price: 129000,
    origin: "국내산",
    category: "의류",
    description: "오리털 90% 충전재 후드 분리 남성 롱 패딩",
  },
  {
    name: "알로에 젤 60캡슐",
    price: 21000,
    origin: "국내산",
    category: "건강",
    description: "제주 유기농 알로에 속살 100% 장 건강 젤 캡슐",
  },
  {
    name: "전동 드라이버 세트",
    price: 42000,
    origin: "중국산",
    category: "생활용품",
    description: "비트 30종 포함 USB 충전 미니 전동 드라이버 세트",
  },
  {
    name: "펫 발톱깎이",
    price: 8500,
    origin: "국내산",
    category: "애완동물",
    description: "안전 스토퍼 내장 반려동물 발톱깎이",
  },
  {
    name: "전기 족욕기",
    price: 52000,
    origin: "중국산",
    category: "가전제품",
    description: "버블 마사지 기능 탑재 자동 온도 유지 족욕기",
  },
  {
    name: "냉동 오징어 1kg",
    price: 15000,
    origin: "국내산",
    category: "음식",
    description: "손질 완료 국내산 냉동 통오징어 1kg",
  },
  {
    name: "여성 겨울 코트",
    price: 145000,
    origin: "국내산",
    category: "의류",
    description: "울 80% 혼방 싱글 버튼 여성 미디 롱코트",
  },
  {
    name: "강황 커큐민 60정",
    price: 26000,
    origin: "인도산",
    category: "건강",
    description: "항염 항산화 강황 커큐민 95% 고함량 영양제 60정",
  },
  {
    name: "접착 테이프 세트",
    price: 7500,
    origin: "국내산",
    category: "생활용품",
    description: "투명 마스킹 포장 테이프 3종 사무 접착 테이프 세트",
  },
  {
    name: "반려묘 숨숨집",
    price: 32000,
    origin: "국내산",
    category: "애완동물",
    description: "아늑한 터널형 고양이 숨숨집 하우스",
  },
  {
    name: "헤어드라이어",
    price: 48000,
    origin: "국내산",
    category: "가전제품",
    description: "음이온 기능 탑재 2200W 고속 헤어드라이어",
  },
  {
    name: "현미 5kg",
    price: 22000,
    origin: "국내산",
    category: "음식",
    description: "전라북도 정읍 친환경 인증 현미 5kg",
  },
  {
    name: "남성 양말 5켤레",
    price: 12000,
    origin: "국내산",
    category: "의류",
    description: "면 85% 남성 기본 발목 양말 5켤레 세트",
  },
  {
    name: "흑마늘 엑기스 30포",
    price: 45000,
    origin: "국내산",
    category: "건강",
    description: "국내산 숙성 흑마늘 농축 엑기스 30포 건강 세트",
  },
  {
    name: "연장 선 멀티탭",
    price: 18000,
    origin: "국내산",
    category: "생활용품",
    description: "개별 스위치 탑재 4구 3m 과부하 차단 멀티탭",
  },
  {
    name: "강아지 치약 세트",
    price: 12000,
    origin: "국내산",
    category: "애완동물",
    description: "칫솔 포함 닭고기 향 강아지 치약 세트",
  },
  {
    name: "웹캠 HD 화질",
    price: 55000,
    origin: "중국산",
    category: "가전제품",
    description: "1080P 자동 초점 마이크 내장 웹캠",
  },
  {
    name: "유기농 두유 10팩",
    price: 12000,
    origin: "국내산",
    category: "음식",
    description: "국산 유기농 콩 100% 무가당 두유 190ml 10팩",
  },
  {
    name: "여성 양말 5켤레",
    price: 12000,
    origin: "국내산",
    category: "의류",
    description: "면 85% 여성 기본 발목 양말 5켤레 패션 세트",
  },
  {
    name: "글루코사민 90정",
    price: 28000,
    origin: "국내산",
    category: "건강",
    description: "관절 건강 연골 보호 글루코사민 콘드로이틴 90정",
  },
  {
    name: "물 걸레 청소포",
    price: 8000,
    origin: "국내산",
    category: "생활용품",
    description: "극세사 물 세정 전용 밀대 전용 청소포 30매",
  },
  {
    name: "고양이 화장실",
    price: 38000,
    origin: "국내산",
    category: "애완동물",
    description: "탈취 필터 내장 후드형 고양이 화장실",
  },
  {
    name: "가습기 초음파",
    price: 42000,
    origin: "중국산",
    category: "가전제품",
    description: "LED 무드등 내장 4L 초음파 가습기",
  },
  {
    name: "고추장 500g",
    price: 9500,
    origin: "국내산",
    category: "음식",
    description: "찹쌀 고추장 2년 전통 숙성 국내산 고추장",
  },
  {
    name: "남성 속옷 세트",
    price: 18000,
    origin: "국내산",
    category: "의류",
    description: "순면 소재 남성 트렁크 박서 속옷 3매 세트",
  },
  {
    name: "가르시니아 60정",
    price: 24000,
    origin: "국내산",
    category: "건강",
    description: "HCA 성분 지방 합성 억제 체중 조절 가르시니아 60정",
  },
  {
    name: "방충망 보수 테이프",
    price: 5500,
    origin: "국내산",
    category: "생활용품",
    description: "자기 접착 방충망 보수 테이프 5cm x 5m",
  },
  {
    name: "펫 영양제",
    price: 29000,
    origin: "국내산",
    category: "애완동물",
    description: "관절 및 피부 건강을 위한 반려동물 종합 영양제",
  },
  {
    name: "전기 다리미",
    price: 35000,
    origin: "국내산",
    category: "가전제품",
    description: "스팀 기능 탑재 자동 전원 차단 전기 다리미",
  },
  {
    name: "냉동 닭가슴살 1kg",
    price: 13000,
    origin: "국내산",
    category: "음식",
    description: "HACCP 인증 냉동 닭가슴살 슬라이스 1kg",
  },
  {
    name: "여성 속옷 세트",
    price: 22000,
    origin: "국내산",
    category: "의류",
    description: "면 소재 여성 브리프 3매 레이스 포인트 세트",
  },
  {
    name: "프로폴리스 30캡슐",
    price: 35000,
    origin: "호주산",
    category: "건강",
    description: "브라질 천연 벌집 추출 프로폴리스 면역 강화 30캡슐",
  },
  {
    name: "창문 단열 필름",
    price: 18000,
    origin: "국내산",
    category: "생활용품",
    description: "단열 단창 보온 에너지 절약 창문 자가 부착 필름",
  },
  {
    name: "강아지 노즈워크 매트",
    price: 16000,
    origin: "국내산",
    category: "애완동물",
    description: "인지 자극용 숨기기 놀이 노즈워크 매트",
  },
  {
    name: "휴대용 배터리",
    price: 45000,
    origin: "중국산",
    category: "가전제품",
    description: "20000mAh 고용량 PD 고속충전 보조 배터리",
  },
  {
    name: "국내산 땅콩버터",
    price: 11000,
    origin: "국내산",
    category: "음식",
    description: "국내산 볶음 땅콩 100% 무가당 크리미 땅콩버터",
  },
  {
    name: "남성 운동복 상하",
    price: 58000,
    origin: "국내산",
    category: "의류",
    description: "흡습 속건 소재 집업 자켓 조거 팬츠 상하 세트",
  },
  {
    name: "스피루리나 90정",
    price: 22000,
    origin: "국내산",
    category: "건강",
    description: "영양 풍부 클로렐라 혼합 식물성 단백질 스피루리나 90정",
  },
  {
    name: "냄비 받침 4개",
    price: 12000,
    origin: "국내산",
    category: "생활용품",
    description: "내열 실리콘 소재 원형 사각 냄비 받침 4개 세트",
  },
  {
    name: "반려견 울타리",
    price: 48000,
    origin: "중국산",
    category: "애완동물",
    description: "조립식 8패널 구성 반려견 안전 울타리",
  },
  {
    name: "스마트 플러그",
    price: 18000,
    origin: "중국산",
    category: "가전제품",
    description: "앱 원격 제어 전력 사용량 측정 스마트 플러그",
  },
  {
    name: "현미 식초 500ml",
    price: 7000,
    origin: "국내산",
    category: "음식",
    description: "국내산 현미 100% 자연 발효 현미 식초 500ml",
  },
  {
    name: "여성 요가복 세트",
    price: 65000,
    origin: "국내산",
    category: "의류",
    description: "고탄력 요가 팬츠와 스포츠브라 여성 요가복 세트",
  },
  {
    name: "카르니틴 60캡슐",
    price: 28000,
    origin: "국내산",
    category: "건강",
    description: "지방 연소 에너지 대사 L-카르니틴 1000mg 60캡슐",
  },
  {
    name: "접이식 사다리",
    price: 55000,
    origin: "국내산",
    category: "생활용품",
    description: "알루미늄 3단 접이식 1.8m 안전 잠금 사다리",
  },
  {
    name: "고양이 사료 5kg",
    price: 38000,
    origin: "국내산",
    category: "애완동물",
    description: "연어와 쌀로 만든 고양이 전용 건식 사료",
  },
  {
    name: "탁상시계 디지털",
    price: 25000,
    origin: "중국산",
    category: "가전제품",
    description: "온도 습도 표시 알람 기능 LED 탁상 디지털 시계",
  },
  {
    name: "냉동 고등어 2마리",
    price: 9500,
    origin: "국내산",
    category: "음식",
    description: "반으로 자른 국내산 자반 고등어 냉동 2마리",
  },
  {
    name: "남성 플리스 자켓",
    price: 72000,
    origin: "국내산",
    category: "의류",
    description: "양면 폴라 플리스 소재 집업 남성 아웃도어 자켓",
  },
  {
    name: "아마씨 분말 300g",
    price: 15000,
    origin: "캐나다산",
    category: "건강",
    description: "오메가3 리그난 식이섬유 풍부 아마씨 분말 300g",
  },
  {
    name: "신발 정리대 4단",
    price: 28000,
    origin: "중국산",
    category: "생활용품",
    description: "조립식 크롬 도금 4단 신발 정리대 수납 선반",
  },
  {
    name: "펫 안심 유모차",
    price: 85000,
    origin: "국내산",
    category: "애완동물",
    description: "접이식 구조의 소형 반려동물 전용 유모차",
  },
  {
    name: "전기 압력솥",
    price: 115000,
    origin: "국내산",
    category: "가전제품",
    description: "10가지 자동 요리 모드 탑재 6L 전기 압력솥",
  },
  {
    name: "국산 잡채 재료 세트",
    price: 16800,
    origin: "국내산",
    category: "음식",
    description: "당면 채소 소스 포함 2인분 국산 잡채 밀키트",
  },
  {
    name: "여성 숏 패딩",
    price: 95000,
    origin: "국내산",
    category: "의류",
    description: "덕다운 충전재 허리선 강조 여성 숏 패딩 자켓",
  },
  {
    name: "여성 갱년기 영양제",
    price: 42000,
    origin: "국내산",
    category: "건강",
    description: "석류 이소플라본 홍삼 여성 갱년기 증상 개선 영양제",
  },
  {
    name: "이불 압축 팩 4개",
    price: 16000,
    origin: "국내산",
    category: "생활용품",
    description: "진공 이불 계절 옷 수납 압축 팩 대형 4개 세트",
  },
  {
    name: "강아지 입욕제",
    price: 7500,
    origin: "국내산",
    category: "애완동물",
    description: "피부 진정 허브 성분 함유 강아지 입욕제",
  },
  {
    name: "칫솔 살균기",
    price: 32000,
    origin: "국내산",
    category: "가전제품",
    description: "UV 살균 기능 탑재 가족용 4구 칫솔 살균기",
  },
  {
    name: "냉동 베이글 4개",
    price: 8500,
    origin: "국내산",
    category: "음식",
    description: "플레인 씨 포함 4종 냉동 수제 베이글 4개",
  },
  {
    name: "남성 니트 베스트",
    price: 35000,
    origin: "국내산",
    category: "의류",
    description: "울 혼방 V넥 단추형 남성 겨울 니트 베스트",
  },
  {
    name: "남성 활력 영양제",
    price: 45000,
    origin: "국내산",
    category: "건강",
    description: "마카 아연 아르기닌 복합 남성 활력 건강 기능 식품",
  },
  {
    name: "청소 솔 세트",
    price: 14000,
    origin: "국내산",
    category: "생활용품",
    description: "욕실 타일 환풍구 청소 전용 브러시 청소 솔 세트",
  },
  {
    name: "고양이 전동 장난감",
    price: 21000,
    origin: "중국산",
    category: "애완동물",
    description: "랜덤 이동 방식의 고양이 전동 쥐 장난감",
  },
  {
    name: "냉온수기 소형",
    price: 185000,
    origin: "국내산",
    category: "가전제품",
    description: "냉수 온수 동시 제공 독립 탱크 방식 소형 냉온수기",
  },
  {
    name: "유기농 견과 믹스",
    price: 18000,
    origin: "국내산",
    category: "음식",
    description: "아몬드 호두 캐슈넛 포함 유기농 견과 믹스 500g",
  },
  {
    name: "여성 롱 스커트",
    price: 42000,
    origin: "국내산",
    category: "의류",
    description: "A라인 플리츠 여성 맥시 길이 플레어 롱 스커트",
  },
  {
    name: "눈 운동기 진동",
    price: 38000,
    origin: "국내산",
    category: "건강",
    description: "온열 진동 마사지 기능 눈 피로 해소 눈 운동기",
  },
  {
    name: "액자 걸이 못 세트",
    price: 8000,
    origin: "국내산",
    category: "생활용품",
    description: "무타공 초강력 접착 액자 걸이 못 패치 세트 20개",
  },
  {
    name: "반려견 배변 패드",
    price: 18000,
    origin: "국내산",
    category: "애완동물",
    description: "100매 초흡수 항균 반려견 배변 훈련 패드",
  },
  {
    name: "노트북 쿨러",
    price: 28000,
    origin: "중국산",
    category: "가전제품",
    description: "대형 팬 듀얼 탑재 LED 조명 노트북 쿨러",
  },
  {
    name: "국내산 사과 3kg",
    price: 19000,
    origin: "국내산",
    category: "음식",
    description: "경북 청송 당도 선별 후지 사과 3kg",
  },
  {
    name: "남성 항균 마스크",
    price: 18000,
    origin: "국내산",
    category: "의류",
    description: "KF94 인증 4중 필터 항균 남성 대형 마스크 10매",
  },
  {
    name: "마사지 볼 세트",
    price: 25000,
    origin: "국내산",
    category: "건강",
    description: "근막 이완 3종 구성 라크로스 스파이크 마사지 볼 세트",
  },
  {
    name: "배터리 AA 16개",
    price: 12000,
    origin: "국내산",
    category: "생활용품",
    description: "국내산 알칼리 AA 사이즈 1.5V 16개 묶음 세트",
  },
  {
    name: "펫 귀 세정제",
    price: 10500,
    origin: "국내산",
    category: "애완동물",
    description: "저자극 성분의 반려동물 귀 전용 세정제",
  },
  {
    name: "전동 칫솔",
    price: 68000,
    origin: "국내산",
    category: "가전제품",
    description: "음파 진동 방식 타이머 내장 충전식 전동 칫솔",
  },
  {
    name: "냉동 팽이버섯",
    price: 4500,
    origin: "국내산",
    category: "음식",
    description: "국내산 청정 팽이버섯 손질 냉동 200g",
  },
  {
    name: "여성 린넨 팬츠",
    price: 48000,
    origin: "국내산",
    category: "의류",
    description: "100% 린넨 와이드 핏 여름 여성 린넨 팬츠",
  },
  {
    name: "저항 밴드 세트",
    price: 22000,
    origin: "국내산",
    category: "건강",
    description: "5단계 강도 구성 폼 그립 탄성 운동 저항 밴드 세트",
  },
  {
    name: "화장실 방향제 세트",
    price: 11000,
    origin: "국내산",
    category: "생활용품",
    description: "시트러스 플로럴 스프레이 화장실 방향 탈취 세트",
  },
  {
    name: "강아지 슬개골 보호대",
    price: 23000,
    origin: "국내산",
    category: "애완동물",
    description: "슬개골 탈구 예방용 강아지 무릎 보호대",
  },
  {
    name: "소형 냉장고",
    price: 235000,
    origin: "국내산",
    category: "가전제품",
    description: "45L 용량 1도어 개인용 소형 냉장고",
  },
  {
    name: "맛김 30봉",
    price: 7900,
    origin: "국내산",
    category: "음식",
    description: "완도산 돌김 참기름 구이 맛김 30봉 선물 세트",
  },
  {
    name: "남성 반팔 셔츠",
    price: 38000,
    origin: "국내산",
    category: "의류",
    description: "면 혼방 체크 패턴 남성 여름 반팔 캐주얼 셔츠",
  },
  {
    name: "요가 매트 6mm",
    price: 32000,
    origin: "국내산",
    category: "건강",
    description: "논슬립 TPE 소재 6mm 두께 접이식 요가 매트",
  },
  {
    name: "냉장고 탈취제 3개",
    price: 8500,
    origin: "국내산",
    category: "생활용품",
    description: "활성탄 숯 성분 냉장고 냄새 흡착 탈취제 3개 세트",
  },
  {
    name: "고양이 물그릇 도자기",
    price: 14000,
    origin: "국내산",
    category: "애완동물",
    description: "무게감 있는 도자기 소재 고양이 전용 물그릇",
  },
  {
    name: "전기 와플 메이커",
    price: 38000,
    origin: "중국산",
    category: "가전제품",
    description: "착탈 세척 가능 플레이트 탑재 전기 와플 메이커",
  },
  {
    name: "건 고추 50g",
    price: 6000,
    origin: "국내산",
    category: "음식",
    description: "경북 영양 태양초 건 고추 50g 분말 원료",
  },
  {
    name: "여성 가디건 세트",
    price: 55000,
    origin: "국내산",
    category: "의류",
    description: "이너 포함 세트 여성 머신 워시 가능 가디건",
  },
  {
    name: "혈압 측정기",
    price: 48000,
    origin: "국내산",
    category: "건강",
    description: "자동 가압 기억 기능 탑재 손목형 혈압 측정기",
  },
  {
    name: "전구 LED 4개 세트",
    price: 14000,
    origin: "국내산",
    category: "생활용품",
    description: "E26 소켓 9W 주백색 LED 전구 4개 절전형 세트",
  },
  {
    name: "반려묘 방석",
    price: 19000,
    origin: "국내산",
    category: "애완동물",
    description: "세탁 가능한 극세사 소재 고양이 방석",
  },
  {
    name: "무선 마우스",
    price: 32000,
    origin: "중국산",
    category: "가전제품",
    description: "2.4GHz 무선 6버튼 인체공학 무선 마우스",
  },
  {
    name: "단호박 1개",
    price: 4500,
    origin: "국내산",
    category: "음식",
    description: "껍질 제거 없이 쪄 먹는 국내산 미니 단호박 1개",
  },
  {
    name: "남성 스트라이프 티",
    price: 24000,
    origin: "국내산",
    category: "의류",
    description: "마린 스트라이프 패턴 남성 반팔 라운드 티셔츠",
  },
  {
    name: "체온계 비접촉",
    price: 35000,
    origin: "국내산",
    category: "건강",
    description: "1초 측정 비접촉 적외선 체온계 이마 귀 겸용",
  },
  {
    name: "면 수건 5매 세트",
    price: 22000,
    origin: "국내산",
    category: "생활용품",
    description: "순면 500g 루프 파일 호텔식 면 수건 5매 세트",
  },
  {
    name: "펫 탈취제",
    price: 8000,
    origin: "국내산",
    category: "애완동물",
    description: "식물성 성분 반려동물 공간 전용 탈취제",
  },
  {
    name: "안경 세척기",
    price: 45000,
    origin: "중국산",
    category: "가전제품",
    description: "초음파 진동 방식 USB 충전 안경 세척기",
  },
  {
    name: "국내산 더덕",
    price: 15000,
    origin: "국내산",
    category: "음식",
    description: "강원도 인제 야생 국내산 더덕 500g",
  },
  {
    name: "여성 오버핏 후디",
    price: 45000,
    origin: "국내산",
    category: "의류",
    description: "기모 안감 캐주얼 오버핏 여성 풀오버 후드 티",
  },
  {
    name: "혈당 측정기 세트",
    price: 45000,
    origin: "국내산",
    category: "건강",
    description: "채혈침 시험지 50매 포함 가정용 혈당 측정기 세트",
  },
  {
    name: "방진 마스크 30매",
    price: 25000,
    origin: "국내산",
    category: "생활용품",
    description: "KF80 일회용 방진 대기 오염 차단 마스크 30매",
  },
  {
    name: "강아지 훈련 클리커",
    price: 3500,
    origin: "국내산",
    category: "애완동물",
    description: "행동 교정 훈련용 강아지 클리커 도구",
  },
  {
    name: "미니 빔프로젝터",
    price: 185000,
    origin: "중국산",
    category: "가전제품",
    description: "1080P 지원 내장 스피커 포함 미니 빔프로젝터",
  },
  {
    name: "냉동 옥수수 1kg",
    price: 8000,
    origin: "미국산",
    category: "음식",
    description: "단옥수수 알갱이 IQF 냉동 옥수수 1kg",
  },
  {
    name: "남성 롱패딩 조끼",
    price: 85000,
    origin: "국내산",
    category: "의류",
    description: "덕다운 충전재 민소매 롱 기장 남성 패딩 조끼",
  },
  {
    name: "산소포화도 측정기",
    price: 28000,
    origin: "국내산",
    category: "건강",
    description: "손가락 착용형 SPO2 맥박 산소포화도 측정기",
  },
  {
    name: "욕조 미끄럼 방지",
    price: 12000,
    origin: "국내산",
    category: "생활용품",
    description: "실리콘 흡착 부착 욕조 바닥 미끄럼 방지 매트",
  },
  {
    name: "고양이 침대 하우스",
    price: 36000,
    origin: "국내산",
    category: "애완동물",
    description: "돔 형태의 따뜻한 고양이 전용 침대 하우스",
  },
  {
    name: "인덕션 1구",
    price: 58000,
    origin: "국내산",
    category: "가전제품",
    description: "화력 10단계 조절 가능 1구 포터블 인덕션",
  },
  {
    name: "양념 간장 게장",
    price: 35000,
    origin: "국내산",
    category: "음식",
    description: "국내산 게 사용 간장 양념 게장 500g 냉장",
  },
  {
    name: "여성 카디건 니트",
    price: 58000,
    origin: "국내산",
    category: "의류",
    description: "울 40% 혼방 오픈 프론트 여성 롱 가디건 니트",
  },
  {
    name: "냉온 팩 세트",
    price: 18000,
    origin: "국내산",
    category: "건강",
    description: "냉찜질 온찜질 겸용 젤 타입 냉온 찜질 팩 세트",
  },
  {
    name: "세탁망 3종 세트",
    price: 9500,
    origin: "국내산",
    category: "생활용품",
    description: "소중대 사이즈 구성 지퍼 잠금 세탁 보호망 세트",
  },
  {
    name: "반려견 쿨링 매트",
    price: 25000,
    origin: "중국산",
    category: "애완동물",
    description: "여름 냉감 소재의 반려견 쿨링 매트",
  },
  {
    name: "전기 온수매트",
    price: 155000,
    origin: "국내산",
    category: "가전제품",
    description: "황토 원적외선 더블 사이즈 전기 온수매트",
  },
  {
    name: "흑임자 가루 300g",
    price: 14000,
    origin: "국내산",
    category: "음식",
    description: "국내산 흑임자 볶음 후 분쇄 흑임자 가루 300g",
  },
  {
    name: "남성 밀리터리 자켓",
    price: 88000,
    origin: "국내산",
    category: "의류",
    description: "멀티 포켓 디자인 카고 스타일 남성 밀리터리 자켓",
  },
  {
    name: "폼 롤러 33cm",
    price: 25000,
    origin: "국내산",
    category: "건강",
    description: "EVA 소재 격자 패턴 근막 이완용 폼 롤러 33cm",
  },
  {
    name: "자동차 방향제",
    price: 7000,
    origin: "국내산",
    category: "생활용품",
    description: "천연 라벤더 향 차량 에어컨 송풍구 클립형 방향제",
  },
  {
    name: "펫 여행 물통",
    price: 12000,
    origin: "국내산",
    category: "애완동물",
    description: "원터치 개폐 기능의 반려동물 외출용 물통",
  },
  {
    name: "핸드 블렌더",
    price: 62000,
    origin: "국내산",
    category: "가전제품",
    description: "700W 다기능 5종 세트 포함 핸드 블렌더",
  },
  {
    name: "국내산 표고 건조",
    price: 18000,
    origin: "국내산",
    category: "음식",
    description: "충북 장수 슬라이스 건 표고버섯 100g",
  },
  {
    name: "여성 리조트 원피스",
    price: 62000,
    origin: "국내산",
    category: "의류",
    description: "플라워 프린트 비치 룩 여성 홀터넥 리조트 원피스",
  },
  {
    name: "발마사지기 전동",
    price: 65000,
    origin: "국내산",
    category: "건강",
    description: "지압 롤러 온열 기능 탑재 발 전용 전동 마사지기",
  },
  {
    name: "청소포 극세사 20매",
    price: 12000,
    origin: "국내산",
    category: "생활용품",
    description: "먼지 제거 세균 차단 재사용 가능 극세사 청소포 20매",
  },
  {
    name: "강아지 수영 조끼",
    price: 27000,
    origin: "국내산",
    category: "애완동물",
    description: "안전 버클 내장 강아지 전용 수영 구명 조끼",
  },
  {
    name: "식품 건조기",
    price: 98000,
    origin: "국내산",
    category: "가전제품",
    description: "5단 트레이 350W 온도 조절 식품 건조기",
  },
  {
    name: "냉동 딸기 1kg",
    price: 12000,
    origin: "국내산",
    category: "음식",
    description: "논산 설향 품종 IQF 방식 냉동 딸기 1kg",
  },
  {
    name: "남성 목폴라 티셔츠",
    price: 32000,
    origin: "국내산",
    category: "의류",
    description: "남성 긴소매 슬림핏 터틀넥 목폴라 티셔츠",
  },
  {
    name: "허리 보호대",
    price: 32000,
    origin: "국내산",
    category: "건강",
    description: "의료 기기 인증 복대 허리 디스크 전용 보호대",
  },
  {
    name: "화분 받침 세트",
    price: 11000,
    origin: "국내산",
    category: "생활용품",
    description: "플라스틱 소재 크기별 4개 구성 화분 물받이 세트",
  },
  {
    name: "고양이 풀 장난감",
    price: 5000,
    origin: "국내산",
    category: "애완동물",
    description: "천연 캣닙 함유 고양이 킥킥이 풀 장난감",
  },
  {
    name: "무드등 타이머",
    price: 22000,
    origin: "중국산",
    category: "가전제품",
    description: "수면 유도 타이머 내장 RGB 무드등",
  },
  {
    name: "국내산 흑미 2kg",
    price: 15000,
    origin: "국내산",
    category: "음식",
    description: "충남 당진 흑미 혼식용 국내산 흑미 2kg",
  },
  {
    name: "여성 레인코트",
    price: 55000,
    origin: "국내산",
    category: "의류",
    description: "방수 투습 소재 후드 포함 여성 경량 레인코트",
  },
  {
    name: "무릎 보호대",
    price: 25000,
    origin: "국내산",
    category: "건강",
    description: "스포츠 운동 무릎 관절 보호용 실리콘 보호대",
  },
  {
    name: "창문 방풍 테이프",
    price: 7000,
    origin: "국내산",
    category: "생활용품",
    description: "스펀지 자기점착 문틈 바람 차단 방풍 테이프 5m",
  },
  {
    name: "반려동물 유산균",
    price: 33000,
    origin: "국내산",
    category: "애완동물",
    description: "장 건강 개선용 반려동물 전용 유산균 영양제",
  },
  {
    name: "스팀 청소기",
    price: 88000,
    origin: "국내산",
    category: "가전제품",
    description: "고온 스팀 살균 기능 탑재 바닥용 스팀 청소기",
  },
  {
    name: "냉동 삼치 2마리",
    price: 11000,
    origin: "국내산",
    category: "음식",
    description: "손질 반으로 자른 국내산 냉동 삼치 2마리",
  },
  {
    name: "남성 바람막이 자켓",
    price: 78000,
    origin: "국내산",
    category: "의류",
    description: "방풍 방수 경량 소재 남성 아웃도어 바람막이 자켓",
  },
  {
    name: "거북목 교정기",
    price: 38000,
    origin: "국내산",
    category: "건강",
    description: "자세 교정 어깨 목 통증 완화 거북목 교정 밴드",
  },
  {
    name: "실내 자전거 수리",
    price: 15000,
    origin: "국내산",
    category: "생활용품",
    description: "타이어 패치 펌프 포함 자전거 수리 공구 키트",
  },
  {
    name: "펫 빗",
    price: 9000,
    origin: "국내산",
    category: "애완동물",
    description: "이중 면 구조의 반려동물 엉킴 제거 전용 빗",
  },
  {
    name: "전기 워머",
    price: 32000,
    origin: "중국산",
    category: "가전제품",
    description: "컵 머그 보온 가능한 USB 타입 전기 컵 워머",
  },
  {
    name: "국산 무농약 배추",
    price: 8000,
    origin: "국내산",
    category: "음식",
    description: "GAP 인증 무농약 국내산 절임 배추 3kg",
  },
  {
    name: "여성 크롭 자켓",
    price: 68000,
    origin: "국내산",
    category: "의류",
    description: "박시 숏 기장 구조 여성 봄 크롭 재킷",
  },
  {
    name: "스트레칭 폼 세트",
    price: 42000,
    origin: "국내산",
    category: "건강",
    description: "단계별 가이드 포함 전신 스트레칭 폼 롤러 세트",
  },
  {
    name: "위생 비닐 장갑 50",
    price: 4500,
    origin: "국내산",
    category: "생활용품",
    description: "식품용 LDPE 위생 비닐 일회용 장갑 50매 세트",
  },
  {
    name: "강아지 도그풀",
    price: 45000,
    origin: "국내산",
    category: "애완동물",
    description: "접이식 구조의 반려견 여름 전용 도그풀",
  },
  {
    name: "이온 헤어 고데기",
    price: 55000,
    origin: "국내산",
    category: "가전제품",
    description: "음이온 세라믹 코팅 3단 온도 이온 헤어 고데기",
  },
  {
    name: "유기농 토마토 1kg",
    price: 13000,
    origin: "국내산",
    category: "음식",
    description: "경남 밀양 유기농 인증 완숙 토마토 1kg",
  },
  {
    name: "남성 기모 레깅스",
    price: 28000,
    origin: "국내산",
    category: "의류",
    description: "기모 안감 보온 기능의 남성 운동용 기모 레깅스",
  },
  {
    name: "아쿠아 슈즈",
    price: 28000,
    origin: "국내산",
    category: "건강",
    description: "미끄럼 방지 배수홀 탑재 수중 운동 전용 아쿠아 슈즈",
  },
  {
    name: "원룸 커튼 봉 세트",
    price: 22000,
    origin: "국내산",
    category: "생활용품",
    description: "길이 조절 가능 텐션 방식 설치 커튼 봉 세트 1.5m",
  },
  {
    name: "고양이 담요",
    price: 16000,
    origin: "국내산",
    category: "애완동물",
    description: "극세사 소재의 보온성 높은 고양이 전용 담요",
  },
  {
    name: "캡슐 커피 머신",
    price: 128000,
    origin: "이탈리아산",
    category: "가전제품",
    description: "다양한 캡슐 호환 19바 압력 에스프레소 머신",
  },
  {
    name: "국내산 도라지",
    price: 12000,
    origin: "국내산",
    category: "음식",
    description: "충북 제천 국내산 채 썬 도라지 500g",
  },
  {
    name: "여성 스트랩 샌들",
    price: 45000,
    origin: "국내산",
    category: "의류",
    description: "스트랩 조절 가능 플랫 소재 여성 여름 샌들",
  },
  {
    name: "스마트 줄넘기",
    price: 32000,
    origin: "중국산",
    category: "건강",
    description: "디지털 카운터 칼로리 측정 기능 스마트 줄넘기",
  },
  {
    name: "생활 공구 세트",
    price: 32000,
    origin: "국내산",
    category: "생활용품",
    description: "드라이버 망치 펜치 포함 가정용 생활 공구 세트",
  },
  {
    name: "반려견 운동장 놀이터",
    price: 72000,
    origin: "국내산",
    category: "애완동물",
    description: "터널 포함 조립식 반려견 실내 운동장 놀이터",
  },
  {
    name: "도어벨 카메라",
    price: 98000,
    origin: "중국산",
    category: "가전제품",
    description: "야간 투시 양방향 통화 스마트 도어벨 카메라",
  },
  {
    name: "냉동 파인애플 1kg",
    price: 9500,
    origin: "필리핀산",
    category: "음식",
    description: "필리핀 직수입 큐브 냉동 파인애플 1kg",
  },
  {
    name: "남성 캡 모자",
    price: 25000,
    origin: "국내산",
    category: "의류",
    description: "볼캡 타입 사이즈 조절 가능 남성 캐주얼 모자",
  },
  {
    name: "손목 보호대 세트",
    price: 19000,
    origin: "국내산",
    category: "건강",
    description: "좌우 2개 구성 손목 터널 증후군 예방 보호대 세트",
  },
  {
    name: "종이 컵 200ml 50개",
    price: 5000,
    origin: "국내산",
    category: "생활용품",
    description: "사무용 개인컵 위생 포장 200ml 종이컵 50개 세트",
  },
  {
    name: "전기 핫플레이트",
    price: 42000,
    origin: "국내산",
    category: "가전제품",
    description: "세라믹 코팅 플레이트 1500W 전기 핫플레이트",
  },
  {
    name: "국내산 연근 500g",
    price: 7000,
    origin: "국내산",
    category: "음식",
    description: "전남 무안 국내산 손질 연근 슬라이스 500g",
  },
  {
    name: "여성 플리츠 스커트",
    price: 38000,
    origin: "국내산",
    category: "의류",
    description: "미디 기장 잔잔 플리츠 여성 봄 하이웨이스트 스커트",
  },
  {
    name: "미세먼지 마스크",
    price: 22000,
    origin: "국내산",
    category: "건강",
    description: "KF94 황사 미세먼지 차단 입체형 마스크 20매 세트",
  },
  {
    name: "일회용 접시 50매",
    price: 6000,
    origin: "국내산",
    category: "생활용품",
    description: "친환경 종이 소재 200mm 원형 일회용 접시 50매",
  },
];
